### ISSUE TITLE
Breaking errors

### ISSUE THREAD

**Issue by karljakober** [Beskhue/ClickerHeroesCalculator#8] opened 2016-12-16 06:46 UTC
Heya! thanks for the calculator!

 It seems like one of your most recent changes may have broken it. I receive the following errors (one seems to be on an interval, and one upon trying to import my save)

![errors](https://cloud.githubusercontent.com/assets/140006/21254141/3e7e0f98-c318-11e6-9afb-5a76e18fb55f.png)

**Comment by tomcur** [comment] 2016-12-16 11:48
Hi! Thank you for opening this issue. I am not able to reproduce this problem. Could you share the save-game that causes these errors and describe steps to reproduce this?

**Comment by tomcur** [comment] 2016-12-31 14:02
I'm closing this issue as I am not able to reproduce it. If you are still having this issue, please comment.

**Closed as completed by tomcur** 2016-12-31 14:02 UTC
Labels: bug, information needed
